#!/usr/bin/env bash
#  Install nginx web server

sudo apt-get update
sudo apt-get upgrate
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
