#!/usr/bin/env bash
#Configure server with and Nginx so that its HTTP
#return the name of the server

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx start
