#!/usr/bin/env bash
#Setup a server to be a Load balancer
#Using HAProxy with roundrobin algorithm

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

sudo sed -i "\$a\
listen backend \n\t bind :80\n\
\tmode http\n\tbalance roundrobin\n\
\tserver 1444-web-01 35.231.103.25:80 check\n\
\tserver 1444-web-02 35.190.157.5:80 check\n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
