#!/usr/bin/env bash
# Bash script with hard process killing

echo "$$" > /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
    trap "echo 'Y U no love me?!'" SIGINT
    trap "rm /var/run/holbertonscript.pid; sudo rm /var/run/holbertonscript.pid; exit" SIGQUIT
    sleep 2
done
