#!/usr/bin/env bash
#fixing 2

sudo pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 600 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
